github: edgardmessias
issuehunt: edgardmessias
ko_fi: edgardmessias
open_collective: edgardmessias
thanks_dev: u/gh/edgardmessias
custom: ['https://www.paypal.com/donate/?hosted_button_id=VM8EPZ6EW6UWS']
