name: "Update translation"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    name: Update POT
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/glpi-project/plugin-builder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          git config --global --add safe.directory "$(pwd)"
          composer install --no-interaction --no-progress --prefer-dist

      - name: Update locales
        run: composer update-locales

      - name: Commit locale updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(locales): update translation files [skip ci]"
          file_pattern: "locales/**"
